### ISSUE TITLE
TypeError: range() integer end argument expected, got str.

### ISSUE THREAD

**Issue by ly2ss** [Marzona/rig-remote#19]
Got running rig-remote. All parts ok except when entered  Min 1000 Max 2000 Interval 25
I get error in console:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in **call**
    return self.func(_args)
  File "/home/zilvis/src/rig-remote/modules/ui.py", line 574, in frequency_start
    self._scan("frequency", "start")
  File "/home/zilvis/src/rig-remote/modules/ui.py", line 622, in _scan
    task = scanning.scan(scanning_task)
  File "/home/zilvis/src/rig-remote/modules/scanning.py", line 137, in scan
    updated_task = self._frequency(task, rigctl)
  File "/home/zilvis/src/rig-remote/modules/scanning.py", line 149, in _frequency
    for i in range(task.monitoring_loops):
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
    return self.func(_args)
  File "/home/zilvis/src/rig-remote/modules/ui.py", line 574, in frequency_start
    self._scan("frequency", "start")
  File "/home/zilvis/src/rig-remote/modules/ui.py", line 622, in _scan
    task = scanning.scan(scanning_task)
  File "/home/zilvis/src/rig-remote/modules/scanning.py", line 137, in scan
    updated_task = self._frequency(task, rigctl)
  File "/home/zilvis/src/rig-remote/modules/scanning.py", line 149, in _frequency
    for i in range(task.monitoring_loops):
TypeError: range() integer end argument expected, got str.

Can't figure out what could be wrong (locale? wrong python version)

**Comment by Marzona** [comment]
Hello,

First of all thanks for reporting this.

I have a question for you, wich branch are you using? I assume master but I
just want to be sure.

Thanks

Regards

Simone Marzona

Linux registered user number: 509183

PGP key ID: 1024D/36F88CC3

Star Trek (2009):

Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
of us and one of you.
James T. Kirk: So get some more guys and then it'll be an even fight

**Comment by ly2ss** [comment]
I used  "git clone https://github.com/marzona/rig-remote.git"
p.s. how I could get devel branch ? I'd like to test it too.

**Comment by Marzona** [comment]
here we are,

https://github.com/Marzona/rig-remote/issues/20

thanks

On Fri, Mar 11, 2016 at 9:51 AM, ly2ss notifications@github.com wrote:

> Got running rig-remote. All parts ok except when entered Min 1000 Max 2000
> Interval 25
> I get error in console:
> Exception in Tkinter callback
> Traceback (most recent call last):
> File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in _call_
> return self.func(
> 
> _args) File "/home/zilvis/src/rig-remote/modules/ui.py", line 574, in
> frequency_start self.scan("frequency", "start") File
> "/home/zilvis/src/rig-remote/modules/ui.py", line 622, in scan task =
> scanning.scan(scanning_task) File
> "/home/zilvis/src/rig-remote/modules/scanning.py", line 137, in scan
> updated_task = self._frequency(task, rigctl) File
> "/home/zilvis/src/rig-remote/modules/scanning.py", line 149, in _frequency
> for i in range(task.monitoring_loops): Exception in Tkinter callback
> Traceback (most recent call last): File
> "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call return
> self.func(_args)
> File "/home/zilvis/src/rig-remote/modules/ui.py", line 574, in
> frequency_start
> self._scan("frequency", "start")
> File "/home/zilvis/src/rig-remote/modules/ui.py", line 622, in _scan
> task = scanning.scan(scanning_task)
> File "/home/zilvis/src/rig-remote/modules/scanning.py", line 137, in scan
> updated_task = self._frequency(task, rigctl)
> File "/home/zilvis/src/rig-remote/modules/scanning.py", line 149, in
> _frequency
> for i in range(task.monitoring_loops):
> TypeError: range() integer end argument expected, got str.
> 
> Can't figure out what could be wrong (locale? wrong python version)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Marzona/rig-remote/issues/19.

## 

 Simone Marzona

 Linux registered user number: 509183

 PGP key ID: 1024D/36F88CC3

 Star Trek (2009):

 Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
 of us and one of you.
 James T. Kirk: So get some more guys and then it'll be an even fight.

**Comment by MaineTim** [comment]
> p.s. how I could get devel branch ? I'd like to test it too.

Use the command: `git checkout devel` in your rig-remote directory.
It should respond:
`Branch devel set up to track remote branch devel from origin.
Switched to a new branch 'devel'`
If so, you're in.
