### ISSUE TITLE
rig-remote gets stuck after a scanning task has completed

### ISSUE THREAD

**Issue by Marzona** [Marzona/rig-remote#30]
when a scanning task completes, the stop button doesn't change to start and pressing the stop button doesn't produce any result, doesn't commute it to start and the program is blocked.
The only way out is killing the python interpreter process.

**Comment by Marzona** [comment]
one behavior is fixedin devel/6c7b2fc6e8d8eed0565cf41369b5b69748f3f2cc

**Comment by MaineTim** [comment]
One error is that scanning.py Line 259  task.new_bookmark_list.append(nbm) needs to be indented.

**Comment by Marzona** [comment]
Yes found it, that's fixed

Simone Marzona

Linux registered user number: 509183

PGP key ID: 1024D/36F88CC3

Star Trek (2009):

Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
of us and one of you.
James T. Kirk: So get some more guys and then it'll be an even fight

**Comment by MaineTim** [comment]
So it's failing in the call to task.stop_scan_button.event_generate("<ButtonRelease-1>"). That method did work when I wrote it a while back, but a lot has changed since then, and frankly I neglected to to check it recently as I haven't had a need for limited passes. Probably I just got lucky in not running into tkinter thread issues initially.

**Comment by Marzona** [comment]
No worries, I'm checking. I'll update the issue.

Regards

Simone Marzona

Linux registered user number: 509183

PGP key ID: 1024D/36F88CC3

Star Trek (2009):

Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
of us and one of you.
James T. Kirk: So get some more guys and then it'll be an even fight

**Comment by Marzona** [comment]
Fixing this issue implies refactoring part of the code that covers the end of the task.

As discussed this is the way we want to go:
- https://github.com/Marzona/rig-remote/issues/33 remove signaling code from the child threads
- https://github.com/Marzona/rig-remote/issues/34 defining a messaging class
- https://github.com/Marzona/rig-remote/issues/35 create unit tests for covering the new logic created with the issues 33 and 34

**Comment by MaineTim** [comment]
GUI code removed from scan thread and thread comms using STMessenger class in tim_devel_fix_issue30.
