### ISSUE TITLE
I want to have bookmarks handling in a dedicated module

### ISSUE THREAD

**Issue by Marzona** [Marzona/rig-remote#36]
Bookmaks handling means:
- a new bookmark class
- methods for adding/removing BM
- methods for handling sets of bookmarks (at least defined and drafted , then with a raise NotImplementedError() in the body).

**Comment by MaineTim** [comment]
Pushed the first iteration of devel-bookmarks-issues-36-53. Just some bits and pieces here, the only thing the class can do is instantiate, and load and save from an existing file. Next up will be to handle new blank bookmark instance creation, and mapping between the class and the ui tree. What you see is basically thinking outloud at this point.

**Comment by MaineTim** [comment]
As of commit d231100, BookmarkSet is integrated into the UI code. It loads, adds, deletes and saves okay. I renamed all the callbacks in ui.py to follow the standard you were using (_cb_foor_bar) so we have continuity, and am converting private methods to an _prefix as I go. Next up is to update the scanning thread code to work with a Bookmarkset. Have also started migrating things to utility.py.

**Comment by Marzona** [comment]
to revive this issue, I started moving the bookmarks logic in  a bookmark.py file, the commit is in devel branch now

ui.py is getting huge:(

**Comment by Marzona** [comment]
I'm closing this, the work done has been merged into devel branch in 283bd98ddc5872a07759b806935fcb7f6a7ce679
