### ISSUE TITLE
Queue handling freeze

### ISSUE THREAD

**Issue by MaineTim** [Marzona/rig-remote#40]
With a single-element queue, the program will freeze if a second event is attempted to be queued before the first one is handled by the scan thread during a bookmark scan. In the past, the events could "buffer up", and the scan thread would handle them in succession when it ran its periodic queue processing code. That logic will need to be changed. 

To reproduce, run a bookmark scan and toggle a checkbutton rapidly. 

Note it doesn't seem to occur during a frequency scan, so either the bookmark code exposes bug somewhere else, or has a bug itself that the single-element queue exposes.

**Comment by MaineTim** [comment]
The put call in send_to_child() in QueueueComms is blocking when the queue is full (there's an unhandled event update), which understandably halts the main thread.  The scan thread halts as well, though, which means the main thread never unblocks. I'm not sure why that's happening. Seems like the scan thread should eventually clear the queue, the main thread call succeeds and we carry on. At worst you'd have a momentary freeze of the GUI. But something is blocking the scan thread too.
Anyway, we can fix the immediate problem by making the put calls non-blocking, but then we'll have to ensure that the program logic can handle the queue, rather than the queue handling itself.

**Comment by Marzona** [comment]
Are we missing the task_done() call somewhere?

Simone Marzona

Linux registered user number: 509183

PGP key ID: 1024D/36F88CC3

Star Trek (2009):

Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
of us and one of you.
James T. Kirk: So get some more guys and then it'll be an even fight

**Comment by Marzona** [comment]
I don't actually understand why we need to queue more than one event..but I
didn't dive deep on this.

Simone Marzona

Linux registered user number: 509183

PGP key ID: 1024D/36F88CC3

Star Trek (2009):

Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
of us and one of you.
James T. Kirk: So get some more guys and then it'll be an even fight

**Comment by MaineTim** [comment]
I think a task_done is only needed when there's been a join call to clear, isn't it?

**Comment by MaineTim** [comment]
> I don't actually understand why we need to queue more than one event.

Because there's no synchronization between the threads, and there doesn't really need to be if the queue is acting as buffer. The event update processing on the scan thread side isn't time critical.

**Comment by Marzona** [comment]
hello Tim,

you' re right.

On Tue, Apr 26, 2016 at 9:21 AM, MaineTim notifications@github.com wrote:

> I think a task_done is only needed when there's been a join call to clear,
> isn't it?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/Marzona/rig-remote/issues/40#issuecomment-214665134

## 

 Simone Marzona

 Linux registered user number: 509183

 PGP key ID: 1024D/36F88CC3

 Star Trek (2009):

 Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
 of us and one of you.
 James T. Kirk: So get some more guys and then it'll be an even fight.

**Comment by MaineTim** [comment]
Why don't we roll back to commit 98580b2, and I'll add back in the one mod that corrects queue checking in the main thread, and then re-think from there.

**Comment by Marzona** [comment]
Sounds a good plan.

Simone Marzona

Linux registered user number: 509183

PGP key ID: 1024D/36F88CC3

Star Trek (2009):

Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
of us and one of you.
James T. Kirk: So get some more guys and then it'll be an even fight

**Comment by MaineTim** [comment]
Okay, I'll do it now.
