### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by MaineTim** [Marzona/rig-remote#45]
Commit 4d4e9ff ignores an Attribute exception that crops up when attempting to run under Windows. That brought to mind the question: is running under Windows currently supported, and if not, should it be, officially or unofficially, at some point in the future?

**Comment by Marzona** [comment]
code reference example :https://github.com/Marzona/rig-remote/commit/4d4e9ff28b9603b7ac4aeaa02fa934970248ad63

**Comment by MaineTim** [comment]
Initial testing looks good with the latest commits. I'm able to run all the main functionality without any glitches, working with gqrx running remotely. Will have to set up pytest on this machine and run the unit tests.

**Comment by Marzona** [comment]
Cool:)

Simone Marzona

Linux registered user number: 509183

PGP key ID: 1024D/36F88CC3

Star Trek (2009):

Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
of us and one of you.
James T. Kirk: So get some more guys and then it'll be an even fight

**Comment by MaineTim** [comment]
Release 2 passes all py.test tests under Windows 7 with python 2.7.11. I'll close this issue, and if we start to see Windows specific issues that I can't fix, I'll start a new "Windows Specific Issues" issue that can serve as a focal point.

**Comment by Marzona** [comment]
excellent.
Thanks a lot.

On Sun, May 1, 2016 at 7:47 PM, MaineTim notifications@github.com wrote:

> Release 2 passes all py.test tests under Windows 7 with python 2.7.11.
> I'll close this issue, and if we start to see Windows specific issues that
> I can't fix, I'll start a new "Windows Specific Issues" issue that can
> serve as a focal point.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/Marzona/rig-remote/issues/45#issuecomment-216063602

## 

 Simone Marzona

 Linux registered user number: 509183

 PGP key ID: 1024D/36F88CC3

 Star Trek (2009):

 Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
 of us and one of you.
 James T. Kirk: So get some more guys and then it'll be an even fight.

**Comment by Marzona** [comment]
Hello Tim,

I'm working on the milestone:
https://github.com/Marzona/rig-remote/milestones/Interaction%20with%20the%20users%20and%20collaborators

ml is ok
writing the wiki now.

regards

On Sun, May 1, 2016 at 7:47 PM, MaineTim notifications@github.com wrote:

> Release 2 passes all py.test tests under Windows 7 with python 2.7.11.
> I'll close this issue, and if we start to see Windows specific issues that
> I can't fix, I'll start a new "Windows Specific Issues" issue that can
> serve as a focal point.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/Marzona/rig-remote/issues/45#issuecomment-216063602

## 

 Simone Marzona

 Linux registered user number: 509183

 PGP key ID: 1024D/36F88CC3

 Star Trek (2009):

 Burly Cadet #1: Hey farmboy. Maybe you can't count. But there are four
 of us and one of you.
 James T. Kirk: So get some more guys and then it'll be an even fight.
