### ISSUE TITLE
rigctl hostname, port not updated, not used in scan thread.

### ISSUE THREAD

**Issue by MaineTim** [Marzona/rig-remote#47]
When the rigctl hostname or port are updated by UI entry, the updated entries are never used. These entry fields need callbacks to update the rigctl instance in the main thread. Further, the rigctl instance created by the main thread isn't passed to the scan thread. Instead, it creates its own, and uses the built-in class defaults, so scanning on a remote machine isn't possible.

Corrective actions: create callbacks for UI hostname and port entries to update the rigctl instance, and pass that instance to the scan thread.

**Comment by Marzona** [comment]
Moreover the rigctl() object is properly instantiated in ui.py (958), and then improperly instantiated in scanning.py (226).

**Comment by Marzona** [comment]
fixed with commit 676e134f0f784c12ac8c5a6e00d1dec4a6f55f03 in branch master and backported into devel with commit 587682a298bf34144eed1591040b21bb3bdfca2f
