### ISSUE TITLE
utility module

### ISSUE THREAD

**Issue by Marzona** [Marzona/rig-remote#48]
We need to create an utility module.

A module that contains "helper methods/classes/objects" and that doesn't import anything from the other application modules.

This module should contain things like is_hostname_valid, as an example

**Comment by MaineTim** [comment]
Moved some helper functions to utility.py in devel in commit 8e2bc75751182b40aaec4e32086363fa659f7808

**Comment by Marzona** [comment]
done in : 
312cb44097f60c2adc2219ac2a7b5b4c97594fc9
