### ISSUE TITLE
Release 2 : Adding a blank bookmark causes traceback.

### ISSUE THREAD

**Issue by MaineTim** [Marzona/rig-remote#50]
I'm on it, but from now on I'm going to add an issue each time I fix something so you get flagged of the commit when it happens. BTW, was able to generate a unit test to duplicate the error, so that's progress on my part. Now I know how to generate unit tests for tkinter events. Who knew?

**Comment by MaineTim** [comment]
Fixed in commit ce3801c, along with pulling the print statements, and changing logger.exception to logger.error to get rid of that traceback.

**Comment by Marzona** [comment]
Great!

**Comment by MaineTim** [comment]
Pushed the same commit to develop.
