### ISSUE TITLE
rig-remote "Framework :: Pytest" category on PyPI?

### ISSUE THREAD

**Issue by nicoddemus** [Marzona/rig-remote#55]
Hi,

I was wondering why `rig-remote` has the `Framework :: Pytest` on [PyPI](https://pypi.python.org/pypi/rig-remote)? That category is meant to be used for pytest **plugins**, and is used by [plugincompat](http://plugincompat.herokuapp.com/) to list and test pytest plugins for compatibility in different pytest and python versions.

**Comment by Marzona** [comment]
Hello nicoddemus,

That's a mistake. I'll fix it asap.

**Comment by Marzona** [comment]
fixed, and thanks for pinging us on this.

**Comment by nicoddemus** [comment]
Cool, thanks! :grin:
