### ISSUE TITLE
Bookmarked frequencies delete functionality

### ISSUE THREAD

**Issue by simontoddm** [Marzona/rig-remote#67]
More of a request as opposed to an issue, but I would like the ability to highlight or select multiply bookmarked frequencies and delete them from the UI. Also, after a delete, I would like the next bookmarked frequency below the deleted bookmarked frequency to be highlighted without having to reselect in the bookmarked window.

**Comment by Marzona** [comment]
Hello,

thanks for this issue. I inserted it in a milestone and I labeled it.

Bookmarks are going to be redesigned/improved as described in the other issues we have, we will see at which stage this feature may be added.

thanks agian.

**Comment by Marzona** [comment]
Hello,

in commit 411ef22bdce5487ebd6a156cc9023de2b7c6b9a8, actually in the branch 2_rig, among all the UI redesigns/changes there is a new remove button, that removes the selected entry from the bookmarks.

While I don't see this as the final solution for your request, it may be an intermediate step.

**Comment by simontoddm** [comment]
Awesome! Thanks!

**Comment by Marzona** [comment]
I'll close this issue.
