### ISSUE TITLE
Import bookmarks errors

### ISSUE THREAD

**Issue by stuzog** [Marzona/rig-remote#88]
I keep getting errors when importing a plain csv file after starting r-r on OS X -- nothing imports:

Bookmarks file (.txt added to conform with Github restrictions):
[rig-bookmarks.csv.txt](https://github.com/Marzona/rig-remote/files/703098/rig-bookmarks.csv.txt)

[rig-remote v.2.1, OS X 10.11.6]

```
bash$ python ./rig-remote.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "/Applications/SDR/rig-remote-2.1/rig_remote/bookmarks.py", line 155, in import_bookmarks
    fileformat = self._detect_format(filename)
  File "/Applications/SDR/rig-remote-2.1/rig_remote/bookmarks.py", line 187, in _detect_format
    raise FormatError()
FormatError

```

**Comment by stuzog** [comment]
[rig-bookmarks.csv.txt](https://github.com/Marzona/rig-remote/files/703084/rig-bookmarks.csv.txt)

**Comment by Marzona** [comment]
this seems the expexted behavior when the format of the bookmarks is not supported. I will check deeper and let you know here.

**Comment by Marzona** [comment]
resolving as the file provided is not of the proper format/type.

**Comment by Marzona** [comment]
I have this: https://github.com/Marzona/rig-remote/issues/84 for providing a clarification on how to write config files

**Comment by stuzog** [comment]
No luck -- downloaded fresh rig-remote, opened it, tried to import bookmarks.csv file from menu -- still won't work, no bookmarks show on OS X 10.11.6 iMac 7,1.

[rig-remote-bookmarks.txt](https://github.com/Marzona/rig-remote/files/752557/rig-remote-bookmarks.txt)

**Comment by Marzona** [comment]
Hello stuzog,

you are using a wrong format. I have https://github.com/Marzona/rig-remote/issues/84 for properly documenting the format, README.md is outdated and misleading now, since the last release.

I updated your txt file (ready to be renamed to csv and imported), it is attached here.

I attach here also a screenshot of the result.

![rig-remote-bookmarks](https://cloud.githubusercontent.com/assets/16374735/22626172/a1b47ae8-eb9f-11e6-9e4f-39551c3ddcd5.png)

[rig-remote-bookmarks.txt](https://github.com/Marzona/rig-remote/files/752942/rig-remote-bookmarks.txt)

regards

**Comment by stuzog** [comment]
Thanks Simone. The file you sent me imported correctly. I'd never have 
guessed the proper format as the sample file in the README at 
<https://github.com/Marzona/rig-remote> is still showing the wrong one. 
Always lots of detail work for a developer! Good work -- thanks! 🙂

**Comment by Marzona** [comment]
;)

**Comment by stuzog** [comment]
Hi Simone,

Scanning works, but it gives a lot of auto-bookmark results using Wide 
FM around a strong FM radio signal. Is there a way of reducing these? It 
would be great to automatically return only the strongest (centre 
frequency) of a signal cluster.

Also, there doesn't seem to be a way of deleting the added 
auto-bookmarks -- how does one do this? If this was possible, it also 
would be useful to be able to sort bookmarks by table header.

I tried re-importing the original bookmarks file, but the newly-added 
auto-bookmarks remain.

Stuart

**Comment by Marzona** [comment]
Hello Stuart,
may I ask to not use this (closed) issue for general discussion around the tool?

- if you have feature request create a new issue it will be classified and delivered according to the priorities.
- if you have general questions on the tool ("how to remove.."), the mailing list is the way to go.

in general, one issue<-> one feature/bug/task to implement, everything else ->mailing list

Regarding the scanning request I created this: https://github.com/Marzona/rig-remote/issues/89 feel free to add there all the details you think are important .

Regarding the deleting the bookmarks, https://github.com/Marzona/rig-remote/wiki/User-Manual will be updated as described here: https://github.com/Marzona/rig-remote/issues/90

regards

**Comment by stuzog** [comment]
OK, will do, thanks.
